### ISSUE TITLE
cmd: -toolexec support

### ISSUE THREAD

**Issue by abhinav** [bracesdev/errtrace#17]
The errtrace command should support being used as -toolexec with `go build`.
This will allow it to rewrite code on the fly without users having to commit to their code directly.

This is not an MVP blocker.

**Comment by prashantv** [comment]
I played around with toolexec mode, and found a couple of packages that work with toolexec mode that we can use as examples: [garble](https://github.com/winstonleedev/garble), and [superpose](https://github.com/cretz/superpose).

A big limitation of toolexec is that [new dependencies can't be added](https://github.com/golang/go/issues/35204), superpose has [some more information](https://github.com/cretz/superpose?tab=readme-ov-file#including-dependency-packages-during-transformation). So a simple implementation will require the user to "opt-in" to errtrace on a per-package basis, which solves one problem -- which packages to instrument, since toolexec is called for all packages, including stdlib + dependencies, but makes the overall experience of using toolexec worse since users will need to remember to opt-in for each pacakge.

Implementation notes:
 * We can make the same `errtrace` binary work in toolexec mode by detecting it via `TOOLEXEC_IMPORTPATH` environment variable
   * `TOOLEXEC_IMPORTPATH` environment variable is not set for the first `compile version` call, e.g.,`.../compile -V=full`.
   * We'll want to return a different build ID for this command, likely a suffix of the orgiinal build command, as it's used as the cache key, and we want toolexec output to be cached separately.
 * In toolexec mode, the rewritten file will be a temporary file, so we'll want to use [line directives](https://pkg.go.dev/cmd/compile#hdr-Compiler_Directives) to fix the paths.

**Comment by prashantv** [comment]
Verified that the `go:linkname` approach [mentioned in a comment](https://github.com/golang/go/issues/35204#issuecomment-633996403) in the above issue does work -- assuming errtrace is part of the final package/binary being built. However, it requires every package where we want to insert a `Wrap` to contain a `go:linkname`, which also requires importing `"unsafe"`.

This only works for non-generic functions, so multi-return wraps like `Wrap2` don't work since [external implementations of generic functions aren't permitted](https://github.com/golang/go/issues/47069).

**Comment by abhinav** [comment]
> This only works for non-generic functions, so multi-return wraps like Wrap2 don't work since https://github.com/golang/go/issues/47069.

If we decide that this approach is a good way forward, we may be able to change the instrumentation code to not use Wrap2. Instead of:

```
return Wrap2(foo())
```

It would do:

```
x, err := foo(); return x, Wrap(err)
```

Where `x` is a unique generated variable name.

If we switch to that, we can deprecate and then delete the WrapN functions.

**Comment by prashantv** [comment]
For future reference, there's also discussion around `-overlay` as an alternative for supporting compile-time instrumentation:
https://github.com/golang/go/issues/69887

I think `-toolexec` is easier for users to use, so no need to change anything, but good to have the option.
